version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:24.21.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package.json" }}
            - v1-npm-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
            - ~/.npm
      - run:
          name: Run tests
          command: npm test

workflows:
  build:
    jobs:
      - test
