version: 2.1

commands:
  install:
    steps:
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package.json" }}
            - v1-npm-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
            - ~/.npm

jobs:
  lint:
    docker:
      - image: cimg/node:24.21.0
    steps:
      - checkout
      - install
      - run:
          name: Run lint
          command: npm run lint

  test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
      - install
      - run:
          name: Run tests
          command: |
            npx mocha --require test/support/env --check-leaks \
              --reporter xunit --reporter-option output=test-results/mocha/results.xml \
              test/ test/acceptance/
      - store_test_results:
          path: test-results
          when: always

workflows:
  build:
    jobs:
      - lint
      - test:
          requires:
            - lint
          matrix:
            parameters:
              node-version: ["22.23.3", "24.21.0"]
